import { sql } from "drizzle-orm";
import { integer, text } from "drizzle-orm/sqlite-core";

/**
 * SQLite (and so Turso) has no date type. Every timestamp is stored as milliseconds since 1970
 * (UTC) in an INTEGER column and read as a JS Date.
 */
export const timestamp = (name: string) => integer(name, { mode: "timestamp_ms" });

/** The database's clock in milliseconds, for defaults and for the gateway's pacing. */
export const nowMs = sql`(cast(unixepoch('subsec') * 1000 as integer))`;

/** Random UUID primary key, generated by the app (SQLite has no gen_random_uuid()). */
export const uuidPrimaryKey = (name = "id") =>
  text(name)
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

/** JSON stored as text; Drizzle parses and serializes it. */
export const json = <T>(name: string) => text(name, { mode: "json" }).$type<T>();

/** SQLite booleans are 0/1 integers. */
export const boolean = (name: string) => integer(name, { mode: "boolean" });
